// Auto-generated by: npx supabase gen types typescript --local > types/database.types.ts
// Re-run after every schema migration.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          display_name: string | null;
          avatar_url: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          display_name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          display_name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      uploads: {
        Row: {
          id: string;
          user_id: string;
          storage_path: string;
          public_url: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          storage_path: string;
          public_url: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          storage_path?: string;
          public_url?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      styles: {
        Row: {
          id: string;
          name: string;
          slug: string;
          prompt_template: string;
          preview_url: string;
          category: string | null;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          prompt_template: string;
          preview_url: string;
          category?: string | null;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          prompt_template?: string;
          preview_url?: string;
          category?: string | null;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      generations: {
        Row: {
          id: string;
          user_id: string;
          upload_id: string;
          replicate_id: string | null;
          status: "pending" | "processing" | "succeeded" | "failed";
          prompt: string | null;
          style_id: string | null;
          ref_photo_url: string | null;
          attributes: Json | null;
          result_url: string | null;
          error_message: string | null;
          created_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          upload_id: string;
          replicate_id?: string | null;
          status?: "pending" | "processing" | "succeeded" | "failed";
          prompt?: string | null;
          style_id?: string | null;
          ref_photo_url?: string | null;
          attributes?: Json | null;
          result_url?: string | null;
          error_message?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          upload_id?: string;
          replicate_id?: string | null;
          status?: "pending" | "processing" | "succeeded" | "failed";
          prompt?: string | null;
          style_id?: string | null;
          ref_photo_url?: string | null;
          attributes?: Json | null;
          result_url?: string | null;
          error_message?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      collections: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          is_default: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          is_default?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          is_default?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      saved_items: {
        Row: {
          id: string;
          collection_id: string;
          generation_id: string;
          user_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          collection_id: string;
          generation_id: string;
          user_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          collection_id?: string;
          generation_id?: string;
          user_id?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "saved_items_generation_id_fkey";
            columns: ["generation_id"];
            isOneToOne: false;
            referencedRelation: "generations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "saved_items_collection_id_fkey";
            columns: ["collection_id"];
            isOneToOne: false;
            referencedRelation: "collections";
            referencedColumns: ["id"];
          },
        ];
      };
      comparison_sessions: {
        Row: {
          id: string;
          user_id: string;
          pinned_image_ids: string[];
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          pinned_image_ids?: string[];
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          pinned_image_ids?: string[];
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: { [_ in never]: never };
  };
};
